"""Portfolio entries curated from public repository READMEs and source trees.

Add a dictionary here to publish another card. Set featured=True to show it
on the homepage too. Keep descriptions specific to implemented work.
"""

PROJECTS = [
    {
        "image": "images/projects/atlas.png",
        "image_alt": "Atlas API documentation showing item and category endpoints with authentication controls.",
        "image_caption": "API documentation",
        "image_width": 1440, "image_height": 1000,
        "title": "Atlas", "category": "Backend development", "label": "ATLAS / TRACKING API",
        "headline": "Everything in its place.", "caption": "ORGANIZE. SEARCH. DISCOVER.", "theme": "atlas",
        "description": "A FastAPI backend for organizing and tracking items with categories, tags, search, filtering, and pagination. JWT authentication supports user accounts, while PostgreSQL and SQLAlchemy model the data relationships. Alembic migrations, Docker setup, and Pytest tests make the project reproducible and testable.",
        "tags": ["Python", "FastAPI", "PostgreSQL", "Docker"],
        "url": "https://github.com/chloemich04/Atlas", "featured": True,
    },
    {
        "image": "images/projects/threatlens.png",
        "image_fit": "cover",
        "image_alt": "ThreatLens dashboard showing cyber incident metrics, a United States threat activity heatmap, regional insights, and an EPSS chart.",
        "image_caption": "Dashboard",
        "image_width": 961, "image_height": 844,
        "title": "Cyber Threat Intelligence & Anomaly Platform", "category": "Cybersecurity · Data visualization",
        "label": "THREAT INTELLIGENCE / DASHBOARD", "headline": "Making threats visible.",
        "caption": "EXPLORE. VISUALIZE. INVESTIGATE.", "theme": "cyber",
        "description": "A cyber-threat intelligence platform that brings incident metrics, a United States activity heatmap, regional insights, and forecast views into a React dashboard. As the backend developer, I built the Django backend and connected our project data to the frontend, making it available for the interface and visualizations.",
        "tags": ["React", "JavaScript", "Python", "Django"],
        "url": "https://github.com/chloemich04/Cyber-Threat-Intelligence-Anomaly-Platform", "featured": True,
    },
    {
        "image": "images/projects/skillforge.png",
        "image_alt": "SkillForge homepage with skill management, activity logging forms, and the local API's built-in sample skills.",
        "image_caption": "Homepage",
        "title": "SkillForge", "category": "Full-stack development", "label": "SKILLFORGE / LEARNING TRACKER",
        "headline": "Build skills. Log progress.", "caption": "LEARN. PRACTICE. REPEAT.", "theme": "forge",
        "description": "A full-stack skill tracker built with a C# ASP.NET Core API and a React/TypeScript interface. Users can create, edit, and delete skills, then record practice dates, time spent, and notes in related activity logs. The project connects structured API models and validation with interactive forms and state updates.",
        "tags": ["C#", "ASP.NET Core", "React", "TypeScript"],
        "url": "https://github.com/chloemich04/SkillForge", "featured": False,
    },
    {
        "image": "images/projects/mini-shop.png",
        "image_alt": "Mini Shop homepage with store navigation, a welcome message, and login and registration links.",
        "image_caption": "Homepage",
        "title": "Mini Shop", "category": "E-commerce · Coursework", "label": "MINI SHOP / VIDEO GAME STORE",
        "headline": "Browse. Cart. Checkout.", "caption": "A FULL-STACK SHOPPING FLOW.", "theme": "shop",
        "description": "An educational video-game storefront with JWT login, customer and store-manager workflows, product search, cart updates, and order history. FastAPI handles application logic and database access through SQLAlchemy, with PostgreSQL hosted on Supabase. Checkout creates demo orders without processing real payments.",
        "tags": ["Python", "FastAPI", "PostgreSQL", "JavaScript"],
        "url": "https://github.com/chloemich04/CSCE-500-Project", "featured": False,
    },
    {
        "image": "images/projects/deepcore.png",
        "image_alt": "DeepCore sorting visualizer showing blue array bars, algorithm selection, sorting controls, and algorithm code.",
        "title": "DeepCore", "category": "Systems programming · Algorithms", "label": "DEEPCORE / PROGRAMMING FOUNDATIONS",
        "headline": "Under the hood.", "caption": "STRUCTURES. ALGORITHMS. SYSTEMS.", "theme": "core",
        "description": "A collection exploring how core programming tools work: linked lists, stacks, queues, binary search trees, and sorting algorithms in C, alongside a mini shell and calculator. A JavaScript visualizer lets users compare sorting algorithms through animated bars, adjustable speed and array size, and comparison and swap counts. Dedicated tests cover the data structures and sorting implementations.",
        "tags": ["C", "Data structures", "Algorithms", "JavaScript"],
        "url": "https://github.com/chloemich04/DeepCore", "featured": False,
    },
    {
        "image": "images/projects/data-analysis.png",
        "image_alt": "Combined data saturation chart comparing cumulative unique theme keywords in ransomware notes, ChainAbuse reports, and Reddit blackmail datasets.",
        "image_caption": "Research chart",
        "image_width": 745, "image_height": 426,
        "title": "Scamming Codebook: Data Analysis", "category": "Research · Data analysis", "label": "SCAMMING CODEBOOK / RESEARCH",
        "headline": "Patterns behind the data.", "caption": "COLLECT. EXAMINE. UNDERSTAND.", "theme": "research",
        "description": "An independently built Python research project examining blackmail scams through ransomware notes, ChainAbuse reports, and Reddit data. I handled data collection, cleaning, analysis, and visualization. Begun as a McNair Scholar, this research continues during my graduate studies as I explore new data and research directions. The saturation chart tracks cumulative unique theme keywords across the datasets to show how additional reports contribute new terms to the analysis.",
        "tags": ["Python", "Data collection", "Research"],
        "url": "https://github.com/chloemich04/Data-Analysis", "featured": False,
    },
    {
        "image": "images/projects/calculator.png",
        "image_alt": "Calculator homepage with a warm brown background, number buttons, and arithmetic controls.",
        "title": "Calculator", "category": "Frontend fundamentals", "label": "CALCULATOR / WEB BASICS",
        "headline": "Make it add up.", "caption": "SMALL PROJECT. CORE SKILLS.", "theme": "calculator",
        "description": "A browser calculator built with HTML, CSS Grid, and event-driven JavaScript. It supports basic arithmetic, decimal input, deleting digits, and clearing calculations, with separate displays for the current input and pending operation. The project demonstrates DOM interaction, calculation state management, and number formatting.",
        "tags": ["HTML", "CSS", "JavaScript"],
        "url": "https://github.com/chloemich04/Calculator", "featured": False,
    },
    {
        "image": "images/projects/tor-anime.png",
        "image_alt": "TorAnime homepage with an anime tracking introduction, community features, navigation, and an event calendar.",
        "image_caption": "Homepage",
        "title": "Anime Tracker", "category": "Web application · Team project", "label": "TOR / ANIME TRACKER",
        "headline": "Your next obsession.", "caption": "DISCOVER. TRACK. CONNECT.", "theme": "anime",
        "description": "A Django and Bootstrap team project for an anime-focused community, bringing user accounts, profiles, discussion forums, and an event calendar together. Users can browse events by month and manage their own event entries, with authentication and ownership checks governing edits. SQLite supports the local application data.",
        "tags": ["Python", "Django", "Bootstrap", "SQLite"],
        "url": "https://gitlab.com/ull-gitlab/sp25-team-projects/sp25-team-011/tor-anime", "featured": True,
    },
    {
        "image": "images/projects/portfolio.png",
        "image_alt": "Chloe Robinson portfolio homepage with an introduction, portrait, and project navigation.",
        "image_caption": "Homepage",
        "title": "This portfolio", "category": "Web development · Personal project", "label": "PERSONAL PORTFOLIO / DJANGO",
        "headline": "A little corner of the web.", "caption": "BUILT WITH CODE & CURIOSITY.", "theme": "portfolio",
        "description": "A personal portfolio built with Django, reusable templates, and a shared project catalog. Responsive cards display real application screenshots and research visuals, while direct contact links make it easy to connect. Lightweight scroll and hover animations respect reduced-motion preferences, and content remains accessible without JavaScript.",
        "tags": ["Python", "Django", "HTML & CSS"],
        "url": "https://github.com/chloemich04/Portfolio", "featured": True,
    },
]
